-- EduPastPapers - Supabase setup for the current GitHub-ready site
-- Run this entire file in Supabase Dashboard -> SQL Editor.
--
-- Frontend-safe key:
--   Use only the Project URL + Publishable/anon key in config.js.
-- NEVER put service_role/secret/database passwords in config.js.

create extension if not exists pgcrypto;

-- =========================
-- TABLES
-- =========================

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text not null default '▤',
  created_at timestamptz not null default now()
);

create table if not exists public.papers (
  id bigint generated by default as identity primary key,
  title text not null,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  year integer not null check (year between 1900 and 2100),
  level text not null default 'University',
  language text not null default 'English',
  description text not null default '',
  file_path text not null,
  downloads integer not null default 0 check (downloads >= 0),
  is_published boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists papers_subject_id_idx on public.papers(subject_id);
create index if not exists papers_year_idx on public.papers(year);
create index if not exists papers_published_idx on public.papers(is_published);

-- =========================
-- ADMIN CHECK
-- =========================

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- Public users need a safe way to increment download counts.
-- It only increments a published paper and does not expose edit access.
create or replace function public.increment_paper_downloads(paper_id bigint)
returns void
language sql
security definer
set search_path = public
as $$
  update public.papers
  set downloads = downloads + 1
  where id = paper_id
    and is_published = true;
$$;

revoke all on function public.increment_paper_downloads(bigint) from public;
grant execute on function public.increment_paper_downloads(bigint) to anon, authenticated;

-- =========================
-- RLS
-- =========================

alter table public.admin_users enable row level security;
alter table public.subjects enable row level security;
alter table public.papers enable row level security;

drop policy if exists "No direct admin_users access" on public.admin_users;
create policy "No direct admin_users access"
on public.admin_users
for all to authenticated
using (false)
with check (false);

drop policy if exists "Public can read subjects" on public.subjects;
create policy "Public can read subjects"
on public.subjects
for select to anon, authenticated
using (true);

drop policy if exists "Admins can insert subjects" on public.subjects;
create policy "Admins can insert subjects"
on public.subjects
for insert to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update subjects" on public.subjects;
create policy "Admins can update subjects"
on public.subjects
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete subjects" on public.subjects;
create policy "Admins can delete subjects"
on public.subjects
for delete to authenticated
using (public.is_admin());

drop policy if exists "Public can read published papers" on public.papers;
create policy "Public can read published papers"
on public.papers
for select to anon, authenticated
using (is_published = true or public.is_admin());

drop policy if exists "Admins can insert papers" on public.papers;
create policy "Admins can insert papers"
on public.papers
for insert to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update papers" on public.papers;
create policy "Admins can update papers"
on public.papers
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete papers" on public.papers;
create policy "Admins can delete papers"
on public.papers
for delete to authenticated
using (public.is_admin());

-- =========================
-- STORAGE
-- =========================
-- Creates the public bucket used by the website.
-- Upload/update/delete are still restricted by RLS below.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'past-papers',
  'past-papers',
  true,
  20971520,
  array['application/pdf']
)
on conflict (id) do update
set public = true,
    file_size_limit = 20971520,
    allowed_mime_types = array['application/pdf'];

drop policy if exists "Admins can upload past papers" on storage.objects;
create policy "Admins can upload past papers"
on storage.objects
for insert to authenticated
with check (
  bucket_id = 'past-papers'
  and public.is_admin()
);

drop policy if exists "Admins can update past papers" on storage.objects;
create policy "Admins can update past papers"
on storage.objects
for update to authenticated
using (
  bucket_id = 'past-papers'
  and public.is_admin()
)
with check (
  bucket_id = 'past-papers'
  and public.is_admin()
);

drop policy if exists "Admins can delete past papers" on storage.objects;
create policy "Admins can delete past papers"
on storage.objects
for delete to authenticated
using (
  bucket_id = 'past-papers'
  and public.is_admin()
);

-- =========================
-- CURRENT SUBJECT LIST
-- =========================

insert into public.subjects (name, icon)
values
  ('Mathematics', '∑'),
  ('Science', '⚛'),
  ('ICT', '⌘'),
  ('Buddhism', '☸'),
  ('English', 'A'),
  ('Sinhala', 'අ'),
  ('Tamil', 'அ'),
  ('History', '▤'),
  ('Health', '◎'),
  ('Physics', '◉'),
  ('Chemistry', '⚗'),
  ('Biology', '♧'),
  ('ET', '◉'),
  ('BST', '⚗'),
  ('SFT', '♧'),
  ('Accounting', '◉'),
  ('Econ', '⚗'),
  ('BS', '♧')
on conflict (name) do nothing;

grant usage on schema public to anon, authenticated;
grant select on public.subjects to anon, authenticated;
grant select on public.papers to anon, authenticated;
grant insert, update, delete on public.subjects to authenticated;
grant insert, update, delete on public.papers to authenticated;
grant usage, select on sequence public.subjects_id_seq to authenticated;
grant usage, select on sequence public.papers_id_seq to authenticated;

-- IMPORTANT ADMIN SETUP:
-- 1. Go to Authentication -> Users in Supabase.
-- 2. Create your admin email/password user.
-- 3. Copy that user's UUID.
-- 4. Run:
--
-- insert into public.admin_users (user_id)
-- values ('PASTE-ADMIN-USER-UUID-HERE')
-- on conflict do nothing;
